@startuml
'https://plantuml.com/sequence-diagram

interface MainScreen
interface newList
interface newItem
interface help

MainScreen <|-- newList
MainScreen <|-- newItem
MainScreen <|-- help


@enduml