@startuml
'https://plantuml.com/sequence-diagram

interface MainScreen
interface newList
interface newItem
interface help
interface Import
class launcher

MainScreen <|- launcher
MainScreen <|-- newList
MainScreen <|-- newItem

MainScreen <|-- Import


@enduml